### PR TITLE
Provide an English version of the README file

### PR DESCRIPTION
**Pull request by Felixnoo**
Signed-off-by: Felixnoo <felixliu@yunify.com>

### CODE REVIEW

**Comment by Felixnoo** [comment]
/assign @LinuxSuRen 
/assign @FeynmanZhou 
I modified the README file. Please take a look when you are available, thanks.

**Review by LinuxSuRen — CHANGES_REQUESTED** [review]
Thanks for providing the English version of the README file. But I'd prefer to have them both instead of removing the Chinese version.

By the way, I believe this PR could fix #75. Normally, we use the following comment to close the corresponding issues.

`fix #75 `

**Comment by LinuxSuRen** [comment]
/retitle Provide an English version of the README file

**Review by LinuxSuRen — APPROVED** [review]
/lgtm

**Comment by LinuxSuRen** [comment]
/lgtm

Try not to use `force-push`. It's very hard to know what changes have you made.

**Comment by LinuxSuRen** [comment]
> By the way, I believe this PR could fix #75. Normally, we use the following comment to close the corresponding issues.

hi @Felixnoo , As you can see, if you don't it like I suggested. The corresponding issue #75 cannot be closed automatically.

**Comment by Felixnoo** [comment]
> > By the way, I believe this PR could fix #75. Normally, we use the following comment to close the corresponding issues.
> 
> hi @Felixnoo , As you can see, if you don't it like I suggested. The corresponding issue #75 cannot be closed automatically.
 
I thought I need to wait for the lgtm label before I add `#75` in my comment. I'll add it in time in future PRs.
BTW, I just made minor format changes so I used `force-push` to clean my commit history. I'll try not to use it in future PRs.

**Comment by LinuxSuRen** [comment]
> I thought I need to wait for the lgtm label before I add #75 in my comment. I'll add it in time in future PRs.

Usually, we put that kind of comment at the beginning of the PR. So GitHub will close the corresponding issue once the PR gets merged.

> BTW, I just made minor format changes so I used force-push to clean my commit history. I'll try not to use it in future PRs.

Got you. Prow can squash the commit history automatically, see also https://github.com/kubesphere/prow-tutorial/pull/30

Anyway, thanks for your contribution.  So glad we can have a better descriptive README file.

**Pull request merged**
